In [2]:
import pandas as pd
import numpy as np
import dask.dataframe as dd

In [3]:
trainDf = pd.read_csv('data/train_v2.csv')
uniqueUsers = trainDf.msno
uniqueUsers

0         ugx0CjOMzazClkFzU2xasmDZaoIqOUAZPsH1q0teWCg=
1         f/NmvEzHfhINFEYZTR05prUdr+E+3+oewvweYz9cCQE=
2         zLo9f73nGGT1p21ltZC3ChiRnAVvgibMyazbCxvWPcg=
3         8iF/+8HY8lJKFrTc7iR9ZYGCG2Ecrogbc2Vy5YhsfhQ=
4         K6fja4+jmoZ5xG6BypqX80Uw/XKpMgrEMdG2edFOxnA=
5         ibIHVYBqxGwrSExE63/omeDD99M5vYB3CN2HzkEY+eM=
6         kVmM8X4iBPCOfK/m1l3KR7LjFoxD1EcKYCc76F5IAWw=
7         moRTKhKIDvb+C8ZHOgmaF4dXMLk0jOn65d7a8tQ2Eds=
8         dW/tPZMDh2Oz/ksduEctJbsz0MXw3kay/1AlZCq3EbI=
9         otEcMhAX3mU4gumUSogqgteN3oaNmhdmTkoof2iRYEE=
10        t5rqTxCnG7s5VBgEfdkQCezv5KBK7+DMujNibYgylrs=
11        dfLS2/Pom6O3iUpo+mf/K1Bc6g+7LFKzoNf+zlJtDoQ=
12        a7AtvhlY8KnKZGpiVe+4HhFerqTEgmno3x7Rc7YGwzw=
13        F45GsXJIeLvzUJqz/v4R/6CVYPdek7K4Leu+aqbCRo8=
14        SJCoxreWp6Cu9WPitvAT6pZ9gChiSR4tWP4lvJGdxSM=
15        Oo2RDQixJ0pRWqec4/CksiKwhz0Za0yU2GIQtKa1JFk=
16        f91n3lDipDjRtAVNgMGnTsxP0VrzDsfB0Hdth12gqQE=
17        /L2095JD4M/BNLTCboucgyuT2i8JIiJ87bOIsxtFvBw=
18        1AzXWFlRO6EfMBzfBdk98sBVnjzY7U1G24mVFNdzGNQ=
19        WkF/FvlzpBLFoa+Hm3hagOfme2pHLE2y+RJ3eGcLT0k=
20        w2O0vchmncaBEQLoC5Pn7qRoSPiJ6X2x5O+woVFDhnY=
21        nGmbdyGVU+LCI2SXyYosErJCCYp371hQNP91BpP2d2I=
22        SlkPQrh6oIqsdpW+Sl2adYlJNEwWSQsIYycM11dSUQg=
23        qpV8BYuYz/Z7LFqEuo2QEMfwWWxdCIQQT4X/XsPXwhc=
24        ePx+sYifOKWLbG1fC8Gy2rjlg92Z7+Blxj94zzyC2+g=
25        Z9Y6f2hXZpPIvbLgHHgUncs7Tb+qmKgGNSwwVAiMlm0=
26        z+DiUWa91dI277IJDsJLTTe61ho3oRnUG/0UXS+y8Mk=
27        TotbNxPUifAoL9diWEMXcRnBgKDStI/a/SdXcf5WhfQ=
28        NTOh3fAZrLoIyE1lxoRpp2lzEraNnnWbUvOhrmO1bUM=
29        wLtPucL8EyK8yUp+F9J1S8Ad/D9CRA8kSB0maalwzjE=
                              ...
970930    rmL1fFghdwK5D2QRNoVR6G6zpLTs+cfYCuQKQ5LmZJo=
970931    KzeT/HbgC16Olk2/JwfdoMgNyRBbYaa4o5fJpd/BF9Q=
970932    DaqeBzX6GHnG6I9bjMaZUNvfgHOSuC7m0iFvQed1G28=
970933    FnoD0d39nrG/UI6s7cEhmna0C+iDq2pf/RRvmrRM4MQ=
970934    dox+xeTWd9a2j9SfbJYF2qWvhXn39wsYydufDoJ777Y=
970935    uHEvWYr9kjyjHeU1fAez+wXUYnFhzueK1lSVwW/+5XU=
970936    PsftdQEI+bQFl8FB2+O4sKM4uRZGO/UvBCDS+ZyWmvk=
970937    PZ2Rnwbw6i+iy8qL/mD/ftCy/eILdvbq6t1N/YP/Rs4=
970938    q18eydRjoRGx2rYbZZxB4jlBZa22VTmCWbgrXEWJfTA=
970939    gBN5EeDyZEdcQbn57I+1+hQgWxhLUFjGNpTaeP62wzU=
970940    i21C/gnxqgu1EIO6eBzGDhqcvuzEfV1u78eYJjLPh5I=
970941    NfsGKIOqjb+zNc96P7TmBuvGRmtYVeMXL8hWfXgk12Q=
970942    RarUowfkW6CrHjw8jMNjFURi17Ja0/docu2tyVfm5jI=
970943    Zkuhc7S+hhMgLkKft6lfrsyi2XHDo6WH7QDdXlringE=
970944    q238ILaUXoyIZpEy4lRXTuKW5Hsko0oWQpGmFxLnyJU=
970945    MqyOPaDM7Jz3kV3fu/h9ilHP3TxLaMFE9raYkEHg5Jg=
970946    5dXGSlRH5LQVFbTUGQwfyyaFb8w/FVqfTS8N4aNEots=
970947    iw+ZE3nH5fhwLvsUCkrzQdKwPEZzMbX+G/RR0J0CpzA=
970948    SjVZDYaiKgEHpFX1PcFDS94b9CFdaHjg78rfumtm/F4=
970949    tcqOxdQ5kBbPc2PBgMz7brdDvDwIR24RqhPuUdymYyo=
970950    dusKsElluiYEfgyc8MPKbyH7MsY6cH9RXqZD3WmxJ7U=
970951    YAm2MZo94+P66Vi7QQai49CZ1MJQrIt96LtXckRg9Co=
970952    5NE9tsGhg7HbFNMdPT+3tytaIKG5013bBQG2vQTe+OI=
970953    eZ3y0lsY2SVZc2h8T3zB454TuBz6oVDMlFsEpEPQclQ=
970954    /QlhSIWEZelYnwttYJSQL50EJJ2yRV+ThQIVQLvctp8=
970955    OHnZbu+EVaP+vN7Z+OfT5OMcp90MWFZonmM0o3pb8FY=
970956    S92bDK//uI6hk3u1vuApro0qJBQOToBozZ7lL1yTC+w=
970957    eUa3xo16vpAjr43Cjlb6Kjf1NTILYyJIkBayJQdXWnw=
970958    iZE41tbAQ65rJq60olkJT4BJzuUAYgQdfbEemXe/TTk=
970959    oECkzJik4wKsbOEVY6UACLbmgM8qymFdb5cJaHrodY8=
Name: msno, Length: 970960, dtype: object

In [4]:
userDf = pd.concat([pd.read_csv('data/user_grouped.csv'),pd.read_csv('data/user_grouped_v2.csv')])
userDf.head()

,msno,month,date,num_25,num_50,num_75,num_985,num_100,num_unq,total_secs
0,+++4vcS9aMH7KWdfh5git6nA5fC5jjisd5H/NcM++WM=,201504,2.015043e+07,1.000000,1.000000,0.000000,0.000000,0.000000,2.000000,97.411000
1,+++EI4HgyhgcJHIPXk/VRP7bt17+2joG39T6oEfJ+tc=,201604,2.016042e+07,2.000000,0.000000,0.000000,0.000000,0.000000,1.000000,56.868000
2,+++FOrTS7ab3tIgIh8eWwX4FqRv8w/FoiOuyXsFvphY=,201609,2.016091e+07,8.571429,1.714286,2.000000,1.000000,24.428571,25.571429,7142.395857
3,+++IZseRRiQS9aaSkH6cMYU6bGDcxUieAi/tH67sC5s=,201501,2.015011e+07,0.761905,0.380952,0.666667,0.380952,87.190476,70.095238,21261.646429
4,+++IZseRRiQS9aaSkH6cMYU6bGDcxUieAi/tH67sC5s=,201502,2.015022e+07,1.769231,0.846154,0.076923,0.384615,59.615385,42.384615,14372.760846

In [5]:
memberDf = pd.read_csv('data/members_v3.csv').loc[:,['msno','bd']]
memberDf.head()

                                           msno  bd
0  Rb9UwLQTrxzBVwCB6+bCcSQWZ9JiNLC9dXtM1oEsZA8=   0
1  +tJonkh+O1CA796Fm5X60UMOtB6POHAwPjbTRVl/EuU=   0
2  cV358ssn7a0f7jZOwGNWS07wCKVqxyiImJUX6xcIwKw=   0
3  9bzDeJP6sQodK73K5CBlJ6fgIQzPeLnRl0p5B77XP+g=   0
4  WFLY3s7z4EZsieHCt63XrsdtfTEmJ+2PnnKLH5GY4Tk=  32

In [6]:
averageAge = 29.490912779050635
memberDf.loc[(memberDf['bd'] > 100) | (memberDf['bd'] < 5),'bd'] = averageAge
memberDf.head()

                                           msno         bd
0  Rb9UwLQTrxzBVwCB6+bCcSQWZ9JiNLC9dXtM1oEsZA8=  29.490913
1  +tJonkh+O1CA796Fm5X60UMOtB6POHAwPjbTRVl/EuU=  29.490913
2  cV358ssn7a0f7jZOwGNWS07wCKVqxyiImJUX6xcIwKw=  29.490913
3  9bzDeJP6sQodK73K5CBlJ6fgIQzPeLnRl0p5B77XP+g=  29.490913
4  WFLY3s7z4EZsieHCt63XrsdtfTEmJ+2PnnKLH5GY4Tk=  32.000000

In [7]:
userDf = userDf.loc[userDf['msno'].isin(uniqueUsers),:]

In [8]:
userDf = userDf.join(memberDf.set_index('msno'), on='msno')

In [9]:
userDf.head()

,msno,month,date,num_25,num_50,num_75,num_985,num_100,num_unq,total_secs,bd
34,+++hVY1rZox/33YtvDgmKA2Frg/2qhkz12B9ylCvh8o=,201611,2.016112e+07,8.533333,4.733333,3.333333,6.733333,31.333333,32.533333,9911.204867,29.490913
35,+++hVY1rZox/33YtvDgmKA2Frg/2qhkz12B9ylCvh8o=,201612,2.016122e+07,6.225806,2.838710,3.161290,4.580645,27.580645,31.580645,8284.258194,29.490913
36,+++hVY1rZox/33YtvDgmKA2Frg/2qhkz12B9ylCvh8o=,201701,2.017012e+07,4.500000,2.300000,2.600000,4.900000,14.600000,23.200000,5262.289233,29.490913
37,+++hVY1rZox/33YtvDgmKA2Frg/2qhkz12B9ylCvh8o=,201702,2.017021e+07,4.296296,2.259259,2.148148,4.222222,17.333333,23.777778,5797.553963,29.490913
38,+++l/EXNMLTijfLBa8p2TUVVVp2aFGSuUI/h7mLmthw=,201501,2.015011e+07,4.833333,0.666667,0.333333,0.166667,6.833333,11.416667,1873.203083,26.000000

In [10]:
#
userDf['bd'] = userDf['bd'].fillna(averageAge)
print userDf.shape
print userDf.dropna(subset=['bd']).shape

(14280430, 11)
(14280430, 11)

In [11]:
print userDf.shape
print userDf.dropna(subset=['total_secs']).shape

(14280430, 11)
(14280430, 11)

In [17]:
grouped = userDf.groupby('msno')
columns = ['num_25','num_50','num_75','num_985','num_100','num_unq','total_secs','bd']
counter = 0
for name, group in grouped:
    if counter < 2:
        counter += 1
        print group.loc[:,columns]
    else:
        break

      num_25    num_50    num_75   num_985    num_100    num_unq   total_secs  \
34  8.533333  4.733333  3.333333  6.733333  31.333333  32.533333  9911.204867
35  6.225806  2.838710  3.161290  4.580645  27.580645  31.580645  8284.258194
36  4.500000  2.300000  2.600000  4.900000  14.600000  23.200000  5262.289233
37  4.296296  2.259259  2.148148  4.222222  17.333333  23.777778  5797.553963
1   6.161290  2.903226  2.419355  4.645161  19.000000  28.548387  6210.577161

           bd
34  29.490913
35  29.490913
36  29.490913
37  29.490913
1   29.490913
      num_25    num_50    num_75   num_985    num_100    num_unq  \
38  4.833333  0.666667  0.333333  0.166667   6.833333  11.416667
39  3.375000  0.625000  0.500000  0.375000  25.375000  17.000000
40  5.285714  2.142857  0.857143  1.142857  10.428571  13.428571
41  1.875000  1.187500  1.312500  0.687500   9.812500   9.812500
42  1.636364  0.454545  0.545455  0.090909  10.272727  11.363636
43  1.181818  0.363636  0.272727  0.272727   3.363636   5.454545
44  2.000000  0.153846  0.307692  0.692308   4.076923   6.923077
45  0.888889  0.444444  0.555556  0.444444   5.888889   7.888889
46  1.708333  1.000000  1.000000  0.750000  58.708333  41.000000
47  2.677419  1.064516  0.612903  0.935484  44.161290  41.193548
48  2.166667  0.633333  0.500000  0.633333  39.200000  33.066667
49  1.774194  0.806452  0.645161  0.741935  27.903226  25.741935
50  2.032258  0.677419  0.645161  0.516129  33.870968  31.903226
51  7.379310  2.000000  1.379310  0.896552  32.310345  38.862069
52  1.428571  0.428571  0.464286  0.464286  18.428571  18.535714
53  1.259259  0.444444  0.629630  0.555556  21.481481  20.777778
54  2.166667  0.900000  0.633333  1.500000  39.733333  35.633333
55  1.703704  0.592593  0.592593  0.629630  21.814815  20.370370
56  2.666667  0.629630  0.629630  0.629630  17.000000  19.000000
57  2.566667  0.900000  1.166667  0.966667  23.633333  24.900000
58  1.892857  1.000000  0.642857  0.678571  23.750000  25.250000
59  1.066667  0.400000  0.466667  0.666667  25.166667  26.366667
60  2.034483  0.793103  0.379310  0.724138  17.931034  18.793103
61  1.387097  0.806452  0.774194  3.096774  17.193548  21.806452
62  3.483871  1.161290  0.967742  2.419355  23.064516  27.096774
63  1.035714  0.607143  0.535714  0.785714  27.214286  25.785714
2   1.535714  0.428571  0.535714  0.428571  17.321429  16.714286

      total_secs    bd
38   1873.203083  26.0
39   6028.793875  26.0
40   3056.292000  26.0
41   2895.172750  26.0
42   2780.402182  26.0
43   1000.655273  26.0
44   1236.438154  26.0
45   1505.682222  26.0
46  14764.950792  26.0
47  11579.592839  26.0
48  10394.433400  26.0
49   7399.227387  26.0
50   8765.448581  26.0
51   8860.286138  26.0
52   4553.982357  26.0
53   5550.176630  26.0
54  10022.056133  26.0
55   5384.766444  26.0
56   4464.692926  26.0
57   6172.605633  26.0
58   6193.243893  26.0
59   6357.544100  26.0
60   4597.857276  26.0
61   4999.303129  26.0
62   6390.492903  26.0
63   6750.280250  26.0
2    4121.830714  26.0

In [12]:
transactionDf = pd.concat([pd.read_csv('data/transactions.csv') , pd.read_csv('data/train_v2.csv')])
transactionDf.head()

,actual_amount_paid,is_auto_renew,is_cancel,is_churn,membership_expire_date,msno,payment_method_id,payment_plan_days,plan_list_price,transaction_date
0,129.0,1.0,0.0,NaN,20151101.0,YyO+tlZtAXYXoZhNr3Vg3+dfVQvrBVGO8j1mfqe4ZHc=,41.0,30.0,129.0,20150930.0
1,149.0,1.0,0.0,NaN,20151031.0,AZtu6Wl0gPojrEQYB8Q3vBSmE2wnZ3hi1FbK1rQQ0A4=,41.0,30.0,149.0,20150930.0
2,129.0,1.0,0.0,NaN,20160427.0,UkDFI97Qb6+s2LWcijVVv4rMAsORbVDT2wNXF0aVbns=,41.0,30.0,129.0,20150930.0
3,149.0,1.0,0.0,NaN,20151128.0,M1C56ijxozNaGD0t2h68PnH2xtx5iO5iR2MVYQB6nBI=,39.0,30.0,149.0,20150930.0
4,149.0,1.0,0.0,NaN,20151121.0,yvj6zyBUaqdbUQSrKsrZ+xNDVM62knauSZJzakS9OW4=,39.0,30.0,149.0,20150930.0

In [13]:
# transactionDf.msno.unique().shape
transactionDf = transactionDf.loc[transactionDf['msno'].isin(uniqueUsers),['msno','is_auto_renew','membership_expire_date', 'transaction_date']]
transactionDf.head()

,msno,is_auto_renew,membership_expire_date,transaction_date
1,AZtu6Wl0gPojrEQYB8Q3vBSmE2wnZ3hi1FbK1rQQ0A4=,1.0,20151031.0,20150930.0
4,yvj6zyBUaqdbUQSrKsrZ+xNDVM62knauSZJzakS9OW4=,1.0,20151121.0,20150930.0
5,KN7I82kjY0Tn76Ny95ncqBUVbO7b8AXrOPqZutKpxIM=,1.0,20151107.0,20150930.0
6,m5ptKif9BjdUghHXXomSezy5ohJiHm85PE13f/3kQaw=,1.0,20151128.0,20150930.0
8,LUPRfoE2r3WwVWhYO/TqQhjrL/qP6CO+/ORUlr7yNc0=,1.0,20151222.0,20150930.0

In [14]:
transactionDf.membership_expire_date = transactionDf.membership_expire_date.fillna(method='ffill')
transactionDf.transaction_date = transactionDf.transaction_date.fillna(method='ffill')
transactionDf.membership_expire_date  = transactionDf.membership_expire_date.astype(int)
transactionDf.transaction_date = transactionDf.transaction_date.astype(int)
expire_year = transactionDf.membership_expire_date//10000
expire_month = (transactionDf.membership_expire_date%10000)//100
expire_day = transactionDf.membership_expire_date//100
tran_year= transactionDf.transaction_date//10000
tran_month = (transactionDf.transaction_date %10000)//100
tran_day = transactionDf.transaction_date//100
# print expire_year
transactionDf['daysBefore'] = (expire_year - tran_year) * 365 + (expire_month - tran_month) * 30 + (expire_day - tran_day)
transactionDf.head()

,msno,is_auto_renew,membership_expire_date,transaction_date,daysBefore
1,AZtu6Wl0gPojrEQYB8Q3vBSmE2wnZ3hi1FbK1rQQ0A4=,1.0,20151031,20150930,31
4,yvj6zyBUaqdbUQSrKsrZ+xNDVM62knauSZJzakS9OW4=,1.0,20151121,20150930,62
5,KN7I82kjY0Tn76Ny95ncqBUVbO7b8AXrOPqZutKpxIM=,1.0,20151107,20150930,62
6,m5ptKif9BjdUghHXXomSezy5ohJiHm85PE13f/3kQaw=,1.0,20151128,20150930,62
8,LUPRfoE2r3WwVWhYO/TqQhjrL/qP6CO+/ORUlr7yNc0=,1.0,20151222,20150930,93

In [57]:
transactionDf.msno.unique().shape

(970960,)

In [35]:
userDf['msno'].unique().shape

(855160,)

In [63]:
trainDf.loc[trainDf.msno.isin(userDf.msno),:].sort_values('msno').head()

                                                msno  is_churn
760876  +++hVY1rZox/33YtvDgmKA2Frg/2qhkz12B9ylCvh8o=         0
798970  +++l/EXNMLTijfLBa8p2TUVVVp2aFGSuUI/h7mLmthw=         0
827003  +++snpr7pmobhLKUgSHTv/mpkqgBT0tQJ0zQj6qKrqc=         0
656165  ++/9R3sX37CjxbY/AaGvbwr3QkwElKBCtSvVzhCBDOk=         0
193862  ++/UDNo9DLrxT8QVGiDi1OnWfczAdEwThaVyD0fXO50=         0

In [ ]:
counter = 0
for name, group in grouped:
    if counter < 2:
        counter += 1
        print group

In [66]:
userDf.shape

(14280430, 11)

In [ ]:
columns = ['num_25','num_50','num_75','num_985','num_100','num_unq','total_secs','bd']
outputList = []
for user in uniqueUsers:
    
    outputList.append(np.array(userDf.loc[userDf['msno'] == user, columns]))
    

np.save('train_v2.npy',np.array(outputList))

In [3]:
userDf.set_index(['msno','month'])

                                                             date     num_25  \
msno                                         month
+++4vcS9aMH7KWdfh5git6nA5fC5jjisd5H/NcM++WM= 201504  2.015043e+07   1.000000
+++EI4HgyhgcJHIPXk/VRP7bt17+2joG39T6oEfJ+tc= 201604  2.016042e+07   2.000000
+++FOrTS7ab3tIgIh8eWwX4FqRv8w/FoiOuyXsFvphY= 201609  2.016091e+07   8.571429
+++IZseRRiQS9aaSkH6cMYU6bGDcxUieAi/tH67sC5s= 201501  2.015011e+07   0.761905
                                             201502  2.015022e+07   1.769231
                                             201503  2.015032e+07   0.967742
                                             201504  2.015042e+07   0.433333
                                             201505  2.015052e+07   0.678571
                                             201506  2.015062e+07   1.000000
                                             201507  2.015072e+07   0.384615
                                             201508  2.015082e+07   0.444444
                                             201509  2.015092e+07   0.357143
                                             201510  2.015102e+07   0.142857
                                             201511  2.015112e+07   0.115385
                                             201512  2.015122e+07   1.933333
                                             201601  2.016011e+07   2.142857
                                             201602  2.016022e+07   1.500000
                                             201603  2.016032e+07   1.740741
                                             201604  2.016042e+07   4.357143
                                             201605  2.016052e+07   0.629630
                                             201606  2.016061e+07   2.640000
                                             201607  2.016072e+07   4.500000
                                             201608  2.016082e+07   3.142857
                                             201609  2.016092e+07   0.866667
                                             201610  2.016102e+07   0.666667
                                             201611  2.016112e+07   0.307692
                                             201612  2.016122e+07   0.884615
                                             201701  2.017012e+07   3.869565
                                             201702  2.017022e+07   1.117647
+++TipL0Kt3JvgNE9ahuJ8o+drJAnQINtxD4c5GePXI= 201512  2.015123e+07   3.000000
...                                                           ...        ...
zzsIerQnY70zKAgAD1GSB89LFnfIxXwXO+FBJEyMbDo= 201703  2.017031e+07   3.166667
zzsusjoGJ6jH+qVF5cMfJGphBO7MR4P4P1rD7qxITX0= 201703  2.017032e+07   6.360000
zzt4LinfZVgufjQc8MVgTz9CwxB9pJtNJDnk3d3F7Ac= 201703  2.017032e+07   2.965517
zztRj67GpP0kdrpfKJ4X4bUrF+ljVCkR0K8cRDIbzRI= 201703  2.017031e+07   2.000000
zztb7cCNxnkeZ33rHQ0Z3cnshdE8gn/nwMTiNP49b4o= 201703  2.017032e+07   2.066667
zztg1DNR0a6n+9+CXd8WAfNZHsl5VvyYC2ngeXlwpkc= 201703  2.017031e+07   2.818182
zzu6u0H6kxDzwhPY7KpdvV4CbMsjIbBVSM6fYXwTrE4= 201703  2.017031e+07   7.000000
zzuGxQfF86Zsx5nqF1Yh+oJpEIfdjFKKYpTqFZMdxzk= 201703  2.017032e+07   8.000000
zzv/igs0VigNppe7WR8qgz1h6aXFFzQLu5paAswIbcQ= 201703  2.017032e+07   3.000000
zzv2n8+r3LGI4gFp6c4hpseYdfHrl829IY3IlA0BF4Q= 201703  2.017032e+07  10.290323
zzvB5JRK4WBwtKJoNtnNF34r5dUAuenPpR9xrxdfMSI= 201703  2.017032e+07   0.375000
zzvRDIlZcYclP7ocM+wG1WUPbUHPtMRPKerl/hionLg= 201703  2.017032e+07  10.928571
zzvhQSh5Xs6/9DO+wUTtEbSZRBHjGIpHMOP2kVMrXmk= 201703  2.017032e+07   3.578947
zzvu4tofjH8jWZ4ubHaMr4K2AB7QARFwzJhcec3TxAU= 201703  2.017032e+07   1.451613
zzwX6rVmjqXmY1e49xsRk0f9WcK5gv6kSWV5bQ0qZqk= 201703  2.017032e+07  51.647059
zzwimfmJBJ4SrRw3bYXQzE9UrizlSE10yI7dHPvG5xM= 201703  2.017032e+07   1.000000
zzwlIVmSuehTevzOi+WkcC7b3+MBYDiE4qybszTyhII= 201703  2.017032e+07   6.032258
zzwsW1MnZalh6V5BwYE+V6hFWyKJYOf+rFd+SWVXxp8= 201703  2.017032e+07   6.666667
zzx1qgX8R9EmT8PAn4/KyQ6s7PuLYTfR8kUCABiCW9E= 201703  2.017031e+07   0.800000
zzx3CIwD26Wwa3Uxdmj848i6g6ctAc4TQtofdSP3JXw= 201703  2.017032e+07   1.321429
zzx4hKiyR9XFEGAr7SAjcCPbKJCZ+IqegWL7dPjPwZk= 201703  2.017031e+07   2.000000
zzxIjlrMxRzNVDD6XqUDRBqkWn7OJ9mzFmFQlfLtLCE= 201703  2.017032e+07   0.916667
zzxPS8+wCuE4HE85EDp4WBHgS5l548vfwXJbQq1HZ9I= 201703  2.017032e+07   9.032258
zzxZeMFx2fjfKZigMnJa2w0EmloDbm8+8nTf/o/00GY= 201703  2.017031e+07   1.000000
zzy0oyiTnRTo5Mbg23oKbBkf9eoaS7+eU4V+d14bzfY= 201703  2.017032e+07   1.800000
zzy7iqSpfcRq7R4hmKKuhI+CJRs79a6pteqEggpiNO0= 201703  2.017032e+07   4.387097
zzyHq6TK2+cBkeGFUHvh12Z7UxFZiSM7dOOSllSBPDw= 201703  2.017032e+07   1.062500
zzz1Dc3P9s53HAowRTrm3fNsWju5yeN4YBfNDq7Z99Q= 201703  2.017031e+07   1.650000
zzzF1KsGfHH3qI6qiSNSXC35UXmVKMVFdxkp7xmDMc0= 201703  2.017031e+07   0.909091
zzzueVTwIa5TjXnG2c77bohCVkuksqLkd5mQTP0wTwQ= 201703  2.017030e+07   2.000000

                                                       num_50    num_75  \
msno                                         month
+++4vcS9aMH7KWdfh5git6nA5fC5jjisd5H/NcM++WM= 201504  1.000000  0.000000
+++EI4HgyhgcJHIPXk/VRP7bt17+2joG39T6oEfJ+tc= 201604  0.000000  0.000000
+++FOrTS7ab3tIgIh8eWwX4FqRv8w/FoiOuyXsFvphY= 201609  1.714286  2.000000
+++IZseRRiQS9aaSkH6cMYU6bGDcxUieAi/tH67sC5s= 201501  0.380952  0.666667
                                             201502  0.846154  0.076923
                                             201503  0.774194  0.483871
                                             201504  0.400000  0.233333
                                             201505  0.464286  0.357143
                                             201506  0.551724  0.517241
                                             201507  0.038462  0.153846
                                             201508  0.185185  0.111111
                                             201509  0.250000  0.285714
                                             201510  0.071429  0.071429
                                             201511  0.115385  0.076923
                                             201512  0.400000  0.233333
                                             201601  0.380952  0.428571
                                             201602  0.285714  0.357143
                                             201603  0.555556  0.370370
                                             201604  1.035714  0.964286
                                             201605  0.185185  0.222222
                                             201606  0.760000  0.360000
                                             201607  0.375000  0.875000
                                             201608  0.809524  0.714286
                                             201609  0.400000  0.533333
                                             201610  0.222222  0.333333
                                             201611  0.115385  0.269231
                                             201612  0.192308  0.346154
                                             201701  0.391304  0.608696
                                             201702  0.352941  0.235294
+++TipL0Kt3JvgNE9ahuJ8o+drJAnQINtxD4c5GePXI= 201512  3.000000  2.000000
...                                                       ...       ...
zzsIerQnY70zKAgAD1GSB89LFnfIxXwXO+FBJEyMbDo= 201703  0.166667  0.000000
zzsusjoGJ6jH+qVF5cMfJGphBO7MR4P4P1rD7qxITX0= 201703  3.240000  1.040000
zzt4LinfZVgufjQc8MVgTz9CwxB9pJtNJDnk3d3F7Ac= 201703  1.103448  1.034483
zztRj67GpP0kdrpfKJ4X4bUrF+ljVCkR0K8cRDIbzRI= 201703  2.000000  0.000000
zztb7cCNxnkeZ33rHQ0Z3cnshdE8gn/nwMTiNP49b4o= 201703  0.833333  0.533333
zztg1DNR0a6n+9+CXd8WAfNZHsl5VvyYC2ngeXlwpkc= 201703  0.181818  0.181818
zzu6u0H6kxDzwhPY7KpdvV4CbMsjIbBVSM6fYXwTrE4= 201703  2.000000  0.000000
zzuGxQfF86Zsx5nqF1Yh+oJpEIfdjFKKYpTqFZMdxzk= 201703  0.933333  0.466667
zzv/igs0VigNppe7WR8qgz1h6aXFFzQLu5paAswIbcQ= 201703  0.000000  0.500000
zzv2n8+r3LGI4gFp6c4hpseYdfHrl829IY3IlA0BF4Q= 201703  1.483871  0.967742
zzvB5JRK4WBwtKJoNtnNF34r5dUAuenPpR9xrxdfMSI= 201703  0.125000  0.250000
zzvRDIlZcYclP7ocM+wG1WUPbUHPtMRPKerl/hionLg= 201703  0.857143  1.964286
zzvhQSh5Xs6/9DO+wUTtEbSZRBHjGIpHMOP2kVMrXmk= 201703  1.842105  0.368421
zzvu4tofjH8jWZ4ubHaMr4K2AB7QARFwzJhcec3TxAU= 201703  0.354839  0.290323
zzwX6rVmjqXmY1e49xsRk0f9WcK5gv6kSWV5bQ0qZqk= 201703  6.882353  3.352941
zzwimfmJBJ4SrRw3bYXQzE9UrizlSE10yI7dHPvG5xM= 201703  0.000000  0.000000
zzwlIVmSuehTevzOi+WkcC7b3+MBYDiE4qybszTyhII= 201703  1.000000  0.677419
zzwsW1MnZalh6V5BwYE+V6hFWyKJYOf+rFd+SWVXxp8= 201703  1.333333  4.000000
zzx1qgX8R9EmT8PAn4/KyQ6s7PuLYTfR8kUCABiCW9E= 201703  0.100000  0.300000
zzx3CIwD26Wwa3Uxdmj848i6g6ctAc4TQtofdSP3JXw= 201703  0.714286  1.035714
zzx4hKiyR9XFEGAr7SAjcCPbKJCZ+IqegWL7dPjPwZk= 201703  0.750000  0.166667
zzxIjlrMxRzNVDD6XqUDRBqkWn7OJ9mzFmFQlfLtLCE= 201703  0.833333  0.250000
zzxPS8+wCuE4HE85EDp4WBHgS5l548vfwXJbQq1HZ9I= 201703  2.387097  1.677419
zzxZeMFx2fjfKZigMnJa2w0EmloDbm8+8nTf/o/00GY= 201703  0.000000  0.000000
zzy0oyiTnRTo5Mbg23oKbBkf9eoaS7+eU4V+d14bzfY= 201703  0.480000  0.160000
zzy7iqSpfcRq7R4hmKKuhI+CJRs79a6pteqEggpiNO0= 201703  2.225806  1.483871
zzyHq6TK2+cBkeGFUHvh12Z7UxFZiSM7dOOSllSBPDw= 201703  0.500000  0.437500
zzz1Dc3P9s53HAowRTrm3fNsWju5yeN4YBfNDq7Z99Q= 201703  0.500000  0.600000
zzzF1KsGfHH3qI6qiSNSXC35UXmVKMVFdxkp7xmDMc0= 201703  0.090909  0.090909
zzzueVTwIa5TjXnG2c77bohCVkuksqLkd5mQTP0wTwQ= 201703  0.000000  0.000000

                                                      num_985     num_100  \
msno                                         month
+++4vcS9aMH7KWdfh5git6nA5fC5jjisd5H/NcM++WM= 201504  0.000000    0.000000
+++EI4HgyhgcJHIPXk/VRP7bt17+2joG39T6oEfJ+tc= 201604  0.000000    0.000000
+++FOrTS7ab3tIgIh8eWwX4FqRv8w/FoiOuyXsFvphY= 201609  1.000000   24.428571
+++IZseRRiQS9aaSkH6cMYU6bGDcxUieAi/tH67sC5s= 201501  0.380952   87.190476
                                             201502  0.384615   59.615385
                                             201503  0.419355  125.774194
                                             201504  0.266667  118.700000
                                             201505  0.321429  119.821429
                                             201506  0.344828  133.586207
                                             201507  0.076923  105.384615
                                             201508  0.074074   86.370370
                                             201509  0.107143  102.214286
                                             201510  0.071429   95.642857
                                             201511  0.076923  115.923077
                                             201512  0.233333  113.000000
                                             201601  0.428571   92.666667
                                             201602  0.285714   31.357143
                                             201603  0.481481  116.259259
                                             201604  0.535714   73.571429
                                             201605  0.074074  105.148148
                                             201606  0.400000   94.080000
                                             201607  0.500000   13.625000
                                             201608  0.809524   14.142857
                                             201609  0.466667   49.266667
                                             201610  0.444444  100.259259
                                             201611  0.115385  116.692308
                                             201612  0.230769  129.807692
                                             201701  0.391304   48.652174
                                             201702  0.764706   52.235294
+++TipL0Kt3JvgNE9ahuJ8o+drJAnQINtxD4c5GePXI= 201512  1.000000   14.000000
...                                                       ...         ...
zzsIerQnY70zKAgAD1GSB89LFnfIxXwXO+FBJEyMbDo= 201703  0.333333    2.833333
zzsusjoGJ6jH+qVF5cMfJGphBO7MR4P4P1rD7qxITX0= 201703  0.600000   95.480000
zzt4LinfZVgufjQc8MVgTz9CwxB9pJtNJDnk3d3F7Ac= 201703  0.689655   23.655172
zztRj67GpP0kdrpfKJ4X4bUrF+ljVCkR0K8cRDIbzRI= 201703  5.000000   34.000000
zztb7cCNxnkeZ33rHQ0Z3cnshdE8gn/nwMTiNP49b4o= 201703  0.566667   73.100000
zztg1DNR0a6n+9+CXd8WAfNZHsl5VvyYC2ngeXlwpkc= 201703  0.090909   26.545455
zzu6u0H6kxDzwhPY7KpdvV4CbMsjIbBVSM6fYXwTrE4= 201703  1.000000   11.000000
zzuGxQfF86Zsx5nqF1Yh+oJpEIfdjFKKYpTqFZMdxzk= 201703  0.600000    4.933333
zzv/igs0VigNppe7WR8qgz1h6aXFFzQLu5paAswIbcQ= 201703  0.000000    9.500000
zzv2n8+r3LGI4gFp6c4hpseYdfHrl829IY3IlA0BF4Q= 201703  0.806452   58.064516
zzvB5JRK4WBwtKJoNtnNF34r5dUAuenPpR9xrxdfMSI= 201703  0.000000   32.875000
zzvRDIlZcYclP7ocM+wG1WUPbUHPtMRPKerl/hionLg= 201703  2.000000   22.178571
zzvhQSh5Xs6/9DO+wUTtEbSZRBHjGIpHMOP2kVMrXmk= 201703  0.315789   39.052632
zzvu4tofjH8jWZ4ubHaMr4K2AB7QARFwzJhcec3TxAU= 201703  0.387097   43.741935
zzwX6rVmjqXmY1e49xsRk0f9WcK5gv6kSWV5bQ0qZqk= 201703  3.588235   33.294118
zzwimfmJBJ4SrRw3bYXQzE9UrizlSE10yI7dHPvG5xM= 201703  0.000000   20.000000
zzwlIVmSuehTevzOi+WkcC7b3+MBYDiE4qybszTyhII= 201703  1.870968   29.290323
zzwsW1MnZalh6V5BwYE+V6hFWyKJYOf+rFd+SWVXxp8= 201703  1.000000   20.666667
zzx1qgX8R9EmT8PAn4/KyQ6s7PuLYTfR8kUCABiCW9E= 201703  0.400000   12.300000
zzx3CIwD26Wwa3Uxdmj848i6g6ctAc4TQtofdSP3JXw= 201703  1.214286   21.607143
zzx4hKiyR9XFEGAr7SAjcCPbKJCZ+IqegWL7dPjPwZk= 201703  0.416667   17.666667
zzxIjlrMxRzNVDD6XqUDRBqkWn7OJ9mzFmFQlfLtLCE= 201703  0.250000    2.250000
zzxPS8+wCuE4HE85EDp4WBHgS5l548vfwXJbQq1HZ9I= 201703  1.548387   54.612903
zzxZeMFx2fjfKZigMnJa2w0EmloDbm8+8nTf/o/00GY= 201703  0.000000   29.000000
zzy0oyiTnRTo5Mbg23oKbBkf9eoaS7+eU4V+d14bzfY= 201703  0.520000  119.080000
zzy7iqSpfcRq7R4hmKKuhI+CJRs79a6pteqEggpiNO0= 201703  1.967742   36.290323
zzyHq6TK2+cBkeGFUHvh12Z7UxFZiSM7dOOSllSBPDw= 201703  0.375000  132.250000
zzz1Dc3P9s53HAowRTrm3fNsWju5yeN4YBfNDq7Z99Q= 201703  0.500000   10.950000
zzzF1KsGfHH3qI6qiSNSXC35UXmVKMVFdxkp7xmDMc0= 201703  0.090909   21.090909
zzzueVTwIa5TjXnG2c77bohCVkuksqLkd5mQTP0wTwQ= 201703  0.000000    1.000000

                                                        num_unq    total_secs
msno                                         month
+++4vcS9aMH7KWdfh5git6nA5fC5jjisd5H/NcM++WM= 201504    2.000000     97.411000
+++EI4HgyhgcJHIPXk/VRP7bt17+2joG39T6oEfJ+tc= 201604    1.000000     56.868000
+++FOrTS7ab3tIgIh8eWwX4FqRv8w/FoiOuyXsFvphY= 201609   25.571429   7142.395857
+++IZseRRiQS9aaSkH6cMYU6bGDcxUieAi/tH67sC5s= 201501   70.095238  21261.646429
                                             201502   42.384615  14372.760846
                                             201503  113.290323  30976.053290
                                             201504  106.133333  29331.011367
                                             201505  111.750000  28944.669750
                                             201506  121.379310  32309.755172
                                             201507   86.461538  25722.816538
                                             201508   47.222222  21415.733741
                                             201509   90.357143  25812.038143
                                             201510   84.785714  24448.461321
                                             201511  100.384615  28832.558192
                                             201512  108.200000  27329.479933
                                             201601   91.047619  22477.892667
                                             201602   33.357143   7756.609429
                                             201603  116.962963  28476.401296
                                             201604   75.357143  17676.922714
                                             201605   87.777778  26525.538519
                                             201606   88.960000  23898.013960
                                             201607   18.000000   3759.568000
                                             201608   19.000000   3952.349238
                                             201609   41.466667  12884.733733
                                             201610   93.814815  25777.857926
                                             201611  105.230769  28657.688231
                                             201612  129.961538  31466.029962
                                             201701   50.130435  12000.289174
                                             201702   43.882353  12963.479235
+++TipL0Kt3JvgNE9ahuJ8o+drJAnQINtxD4c5GePXI= 201512   22.000000   3661.527000
...                                                         ...           ...
zzsIerQnY70zKAgAD1GSB89LFnfIxXwXO+FBJEyMbDo= 201703    4.333333    875.190500
zzsusjoGJ6jH+qVF5cMfJGphBO7MR4P4P1rD7qxITX0= 201703   92.680000  23669.063000
zzt4LinfZVgufjQc8MVgTz9CwxB9pJtNJDnk3d3F7Ac= 201703   21.137931   5678.248207
zztRj67GpP0kdrpfKJ4X4bUrF+ljVCkR0K8cRDIbzRI= 201703   43.000000  10087.694000
zztb7cCNxnkeZ33rHQ0Z3cnshdE8gn/nwMTiNP49b4o= 201703   68.133333  18563.491567
zztg1DNR0a6n+9+CXd8WAfNZHsl5VvyYC2ngeXlwpkc= 201703   17.818182   6770.411909
zzu6u0H6kxDzwhPY7KpdvV4CbMsjIbBVSM6fYXwTrE4= 201703   11.000000   3632.295000
zzuGxQfF86Zsx5nqF1Yh+oJpEIfdjFKKYpTqFZMdxzk= 201703   12.600000   1603.169133
zzv/igs0VigNppe7WR8qgz1h6aXFFzQLu5paAswIbcQ= 201703   13.000000   2695.582500
zzv2n8+r3LGI4gFp6c4hpseYdfHrl829IY3IlA0BF4Q= 201703   38.193548  14630.344194
zzvB5JRK4WBwtKJoNtnNF34r5dUAuenPpR9xrxdfMSI= 201703   33.125000   7895.032250
zzvRDIlZcYclP7ocM+wG1WUPbUHPtMRPKerl/hionLg= 201703   22.214286   5630.754393
zzvhQSh5Xs6/9DO+wUTtEbSZRBHjGIpHMOP2kVMrXmk= 201703   43.947368   9607.439316
zzvu4tofjH8jWZ4ubHaMr4K2AB7QARFwzJhcec3TxAU= 201703   34.612903  10097.887161
zzwX6rVmjqXmY1e49xsRk0f9WcK5gv6kSWV5bQ0qZqk= 201703   43.764706   9492.068059
zzwimfmJBJ4SrRw3bYXQzE9UrizlSE10yI7dHPvG5xM= 201703   21.000000   4700.720000
zzwlIVmSuehTevzOi+WkcC7b3+MBYDiE4qybszTyhII= 201703   29.193548   8012.149581
zzwsW1MnZalh6V5BwYE+V6hFWyKJYOf+rFd+SWVXxp8= 201703   27.666667   5874.882333
zzx1qgX8R9EmT8PAn4/KyQ6s7PuLYTfR8kUCABiCW9E= 201703   11.500000   2772.714200
zzx3CIwD26Wwa3Uxdmj848i6g6ctAc4TQtofdSP3JXw= 201703   10.000000   5503.076857
zzx4hKiyR9XFEGAr7SAjcCPbKJCZ+IqegWL7dPjPwZk= 201703   19.250000   4282.908167
zzxIjlrMxRzNVDD6XqUDRBqkWn7OJ9mzFmFQlfLtLCE= 201703    3.166667    777.793000
zzxPS8+wCuE4HE85EDp4WBHgS5l548vfwXJbQq1HZ9I= 201703   63.419355  14814.123774
zzxZeMFx2fjfKZigMnJa2w0EmloDbm8+8nTf/o/00GY= 201703   21.500000   6586.085500
zzy0oyiTnRTo5Mbg23oKbBkf9eoaS7+eU4V+d14bzfY= 201703   67.280000  23973.762880
zzy7iqSpfcRq7R4hmKKuhI+CJRs79a6pteqEggpiNO0= 201703   16.548387   8646.443968
zzyHq6TK2+cBkeGFUHvh12Z7UxFZiSM7dOOSllSBPDw= 201703   99.437500  29865.424312
zzz1Dc3P9s53HAowRTrm3fNsWju5yeN4YBfNDq7Z99Q= 201703   12.000000   3047.686250
zzzF1KsGfHH3qI6qiSNSXC35UXmVKMVFdxkp7xmDMc0= 201703   18.363636   5411.425364
zzzueVTwIa5TjXnG2c77bohCVkuksqLkd5mQTP0wTwQ= 201703    3.000000    232.490000

[27862865 rows x 8 columns]

In [ ]:
trainDf = pd.read_csv('data/train_v2.csv')